spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: secret
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect